### PR TITLE
Adding OctoEverywhere information in the blog post about remote access.

### PR DESCRIPTION
**Pull request by QuinnDamerell**
It would be great to get this added to this page since it's at the top of the search results for most remote related queries. I'm still trying to drum up more support for the service to keep it alive, and I hope this might help!

I tried my best to keep the description objective, but please free free to make or suggest any edits. :)

### CODE REVIEW

**Comment by QuinnDamerell** [comment]
Friendly Ping!

It looks like from the commit history @foosel usually does the PRs, can I get your thoughts on this one? Thanks!

**Comment by foosel** [comment]
I was on vacation until just now ;)

Since this was a guest post by @jubaleth however and it's *his* name in the by-line, I'll have to refer this to him.

Starting to think it might make sense to add a wiki post to the forums with a list of remote access solutions and link THAT from the post, prominently. I'm sure there'll be a fluctuation in options in the future. Thoughts?

**Comment by jubaleth** [comment]
Heya!

So regarding the addition, I'm perfectly fine with that. I think @foosel's idea of perhaps us putting together a wiki page with the recommendations and simply linking to that from the blog/forums is a good idea, saves us from having to keep altering the post.

**Review by jubaleth — APPROVED** [review]

**Comment by QuinnDamerell** [comment]
Thanks, both of you @foosel and @jubaleth for the quick response! I appreciate it!

**Pull request merged**
